In [1]:
#classification
from sklearn.datasets import load_iris
li=load_iris()
x=li.data
y=li.target
from sklearn.preprocessing import MinMaxScaler
scale=MinMaxScaler()
x1=scale.fit_transform(x)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [2]:
#binary to integer
import numpy as np
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
y1=ohe.fit_transform(y[:,np.newaxis]).toarray()
y2=y1.astype('int')
y2

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [3]:
#split data
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x1,y2,test_size=0.2)

In [4]:
from keras.models import Sequential
from keras.layers import Dense
model=Sequential()
model.add(Dense(12,activation='relu',input_dim=4))
model.add(Dense(12,activation='relu'))
model.add(Dense(3,activation='softmax'))
model.compile(optimizer='adam',loss='categorical_crossentropy')
model.fit(xtrain,ytrain,epochs=100)

Epoch 1/100
4/4 [==============================] - 1s 11ms/step - loss: 1.0783
Epoch 2/100
4/4 [==============================] - 0s 9ms/step - loss: 1.0676
Epoch 3/100
4/4 [==============================] - 0s 9ms/step - loss: 1.0562
Epoch 4/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0452
Epoch 5/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0349
Epoch 6/100
4/4 [==============================] - 0s 9ms/step - loss: 1.0246
Epoch 7/100
4/4 [==============================] - 0s 6ms/step - loss: 1.0149
Epoch 8/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0055
Epoch 9/100
4/4 [==============================] - 0s 6ms/step - loss: 0.9957
Epoch 10/100
4/4 [==============================] - 0s 4ms/step - loss: 0.9864
Epoch 11/100
4/4 [==============================] - 0s 5ms/step - loss: 0.9767
Epoch 12/100
4/4 [==============================] - 0s 4ms/step - loss: 0.9676
Epoch 13/100
4/4 [==============================] - 0s 4ms/s

In [5]:
ypred=model.predict(xtest)


1/1 [==============================] - 0s 200ms/step


In [6]:
for i in range(len(ypred)):
  j=np.argmax(ypred[i,:])
  ypred[i,0]=0
  ypred[i,1]=0
  ypred[i,2]=0
  ypred[i,j]=1

In [7]:
ypred.astype('int')

array([[0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0]])

In [8]:
def accuracy(y1,y):
  correct=0
  for a,b in zip(y1,y):
    if a==b:
      correct+=1
  return correct/len(y1)

In [9]:
accuracy(ypred.tolist(),ytest.tolist())

0.4

In [10]:
from sklearn.metrics import accuracy_score
accuracy_score(ytest,ypred)

0.4

In [11]:
#for accuracy
#method 1
# we have two methods one is precision_score and another is recall_score
from sklearn.metrics import precision_score
precision_score([1,0,0],[1,1,1])
sum=0
for i in range(len(ypred)):
  a=precision_score(ytest[i],ypred[i])
  sum+=a
sum/=len(ypred)
sum



0.4

In [12]:
# method two recall_score
from sklearn.metrics import recall_score
precision_score([1,0,0],[1,1,1])
sum=0
for i in range(len(ypred)):
  a=recall_score(ytest[i],ypred[i])
  sum+=a
sum/=len(ypred)
sum



0.4